name: CD Workflow

on:
  workflow_run:
    workflows: ["ci development"] 
    types:
      - completed
  workflow_dispatch: 

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder step
        run: echo "This is a placeholder job."


  deploy-server:
    runs-on: ubuntu-latest
    environment: "develop"
    needs: ["ci-development"]

    steps:
      - name: "complete"
        run: |
          echo "ok cd"