name: CD Workflow

on:
  workflow_run:
    workflows: ["ci development"] 
    types:
      - completed

jobs:
  push-image:
    runs-on: ubuntu-latest
    environment: "develop"
    needs: ["ci-development"]

    steps:
      - name: "complete"
        run: |
          echo "ok cd"